apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGODB_URL: {{ .Values.secrets.mongodbUrl | b64enc | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.adminJwtSecret | b64enc | quote }}