apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.deployment.serviceName }}
  labels:
    app: {{ .Values.deployment.serviceName }}
spec:
  type:  {{ .Values.deployment.serviceType }}
  selector:
    app: {{ .Values.deployment.podName }}
  ports:
    - port: 3200
      targetPort: 7000
      nodePort: 31522