apiVersion: v1
kind: Secret
metadata:
  name: app-feed-secrets
type: Opaque
data:
  MONGODB_URL: {{ .Values.secrets.mongodbUrl | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}