apiVersion: v1
kind: Secret
metadata:
  name: app-user-secrets
type: Opaque
data:
  MONGODB_URL: {{ .Values.secrets.mongodbUrl | b64enc | quote }}
  RESEND_API: {{ .Values.secrets.resendAPI | b64enc | quote }}
  SEND_EMAIL: {{ .Values.secrets.sendEmail | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  AWS_REGION: {{ .Values.secrets.awsRegion | b64enc | quote }}
  ADMIN_JWT_SECRET: {{ .Values.secrets.adminJwtSecret | b64enc | quote }}