apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.imageName }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 4001
              protocol: TCP
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: MONGODB_URL
            - name: RESEND_API
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: RESEND_API
            - name: SEND_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: SEND_EMAIL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: JWT_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: AWS_REGION
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-user-secrets
                  key: ADMIN_JWT_SECRET
                  