apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: frontend-service
build:
  artifacts:
    - image: aravsanj/opine-frontend-service
      context: ../../../frontend/opine-frontend-nextjs
      sync:
        infer:
          - "**/*"
  local:
    push: false
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: frontend-service
        chartPath: .
        valuesFiles:
          - values.yaml
        version: 0.1.0
