apiVersion: v1
kind: Secret
metadata:
  name: app-channel-secrets
type: Opaque
data:
  MONGODB_URL: {{ .Values.secrets.mongodbUrl | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  ADMIN_JWT_SECRET: {{ .Values.secrets.adminJwtSecret | b64enc | quote }}